from pathlib import Path
from typing import Protocol


class Storage(Protocol):
    def upload(self, source: Path, key: str) -> None: ...
    def download(self, key: str, destination: Path) -> None: ...
    def delete(self, key: str) -> None: ...
    def exists(self, key: str) -> bool: ...
    def get_url(self, key: str) -> str: ...
    def get_signed_url(self, key: str, expires: int = 300) -> str: ...
